language: python
matrix:
  include:
    - dist: trusty
      python: 2.7
    - dist: xenial
      python: 3.7
      env:
        - nodoc=true
services:
  - mongodb
env: TMPDIR=$PWD/tmp
install:
  - python setup.py install
script:
  - package=workflowwebtools opsspace-test
