language: python
cache: pip
python: 2.7
sudo: required
dist: trusty
env: CHECKDOC=true
install:
  - pip install git+https://github.com/eliben/pycparser@release_v2.14
#  - git clone https://github.com/CMSCompOps/OpsSpace.git
  - git clone https://github.com/dabercro/OpsSpace.git
script: OpsSpace/test/package_test.sh
