language: python
matrix:
  include:
    - dist: xenial
      python: 3.7
      env:
        - nodoc=true
services:
  - mongodb
env: TMPDIR=$PWD/tmp
install:
  - pip install .
script:
  - pip list
  - package=workflowwebtools opsspace-test
