language: python
cache: pip
python: 2.7
sudo: required
dist: trusty
services:
  - mongodb
#addons:
#  apt:
#    sources: debian-sid
#    packages: shellcheck
env: TMPDIR=$PWD/tmp
install:
  - test -d $TMPDIR/workflowinfo || mkdir -p $TMPDIR/workflowinfo
  - git clone --branch v0.7 https://github.com/CMSCompOps/OpsSpace.git
script: OpsSpace/test/package_test.sh
